[build]
  # Directory da pubblicare (root della repo, dove si trova domicilio.html)
  publish = "."

  # Nessun comando di build, sito statico
  command = ""

# (Opzionale) Directory per funzioni serverless
# functions = "netlify/functions"
